# Generated by Django 4.2.11 on 2025-05-04 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Укажите почту', max_length=254, unique=True, verbose_name='Почта')),
                ('phone_number', models.CharField(blank=True, help_text='Укажите номер телефона', max_length=15, null=True, verbose_name='Номер телефона')),
                ('city', models.CharField(blank=True, help_text='Укажите город', max_length=40, null=True, verbose_name='Город')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Укажите дату оплаты', null=True, verbose_name='Дата оплаты')),
                ('payment_amount', models.PositiveIntegerField(blank=True, default=0, help_text='Укажите сумму оплаты', null=True, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'наличные'), ('transfer', 'перевод на счет')], default='cash', help_text='Выберите способ оплаты', max_length=255, null=True, verbose_name='Способ оплаты')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id сессии')),
                ('link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Cсылка на оплату')),
                ('course_paid', models.ForeignKey(blank=True, help_text='Укажите оплаченный курс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_course', to='lms.course', verbose_name='Оплаченный курс')),
                ('lesson_paid', models.ForeignKey(blank=True, help_text='Укажите оплаченный урок', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_lesson', to='lms.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(help_text='Укажите плательщика', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
