# Generated by Django 4.2.20 on 2025-05-04 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_subscription_options_remove_course_preview_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, help_text='Укажите дату оплаты', null=True, verbose_name='Дата оплаты')),
                ('payment_amount', models.PositiveIntegerField(blank=True, default=0, help_text='Укажите сумму оплаты', null=True, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'наличные'), ('transfer', 'перевод на счет')], default='cash', help_text='Выберите способ оплаты', max_length=255, null=True, verbose_name='Способ оплаты')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id сессии')),
                ('link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Cсылка на оплату')),
                ('course_paid', models.ForeignKey(blank=True, help_text='Укажите оплаченный курс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_course', to='lms.course', verbose_name='Оплаченный курс')),
                ('lesson_paid', models.ForeignKey(blank=True, help_text='Укажите оплаченный урок', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_lesson', to='lms.lesson', verbose_name='Оплаченный урок')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Укажите номер телефона', max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Укажите город', max_length=40, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Укажите почту', max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AddField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(help_text='Укажите плательщика', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик'),
        ),
    ]
