# Generated by Django 5.1.7 on 2025-03-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_payment_paid_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Укажите сумму пожертвования',
                                                       verbose_name='Сумма пожертвования')),
                ('session_id', models.CharField(help_text='Укажите ID сессии, к которой относится пожертвование',
                                                max_length=255, verbose_name='ID сессии')),
                ('link', models.URLField(blank=True,
                                         help_text='Укажите ссылку, связанную с пожертвованием '
                                                   '(например, на страницу оплаты)',
                                         max_length=400, null=True, verbose_name='Ссылка на пожертвование')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='donations', to=settings.AUTH_USER_MODEL,
                                           verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пожертвование',
                'verbose_name_plural': 'Пожертвования',
            },
        ),
    ]
