# Generated by Django 5.1.6 on 2025-03-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название курса', max_length=200, verbose_name='Название курса')),
                ('preview_image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='courses/previews/', verbose_name='Превью')),
                ('description', models.TextField(help_text='Введите описание курса', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название урока', max_length=200, verbose_name='Название урока')),
                ('description', models.TextField(help_text='Введите описание урока', verbose_name='Описание')),
                ('preview_image', models.ImageField(blank=True, help_text='Загрузите изображение ', null=True, upload_to='lessons/previews/', verbose_name='Превью')),
                ('video_link', models.URLField(blank=True, help_text='Введите ссылку на видео', null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.course')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
