# Generated by Django 5.1.6 on 2025-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
    ]
