# Generated by Django 4.2.20 on 2025-05-04 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0004_coursesubscription_delete_subscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSubscription',
            new_name='Subscription',
        ),
    ]
