# Generated by Django 5.1.7 on 2025-03-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
